### ISSUE TITLE
MaterialStaggeredGridView in TastesFragment

### ISSUE THREAD

**Issue by claudiopastorini** [PRIMETIME4U/PRIMETIME4U-baseclient#1]
Use [this](https://github.com/dexafree/MaterialList#materialstaggeredgridview) in TastesFragment

**Comment by giovannicolonna** [comment]
if i swipe the tab, the tastes cards go away... i will work on it

**Comment by giovannicolonna** [comment]
MaterialStaggeredGridView has been implemented into Tastes Fragment
