### ISSUE TITLE
Pop-up menu card

### ISSUE THREAD

**Issue by claudiopastorini** [PRIMETIME4U/PRIMETIME4U-baseclient#33]
Create simple pop-up attached at image
http://stackoverflow.com/questions/26628652/how-to-add-overflow-icon-items-in-a-card-in-android

**Comment by giovannicolonna** [comment]
Improvements:
- substitute "dettagli" with "già visto"
- open details by clicking the image

**Comment by giovannicolonna** [comment]
My improvements are fixed now
